name: Package img2zpl

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            CMD_BUILD: pyinstaller --clean -y --distpath ./dist/linux img2zpl.spec
            OUT_FILE: linux/img2zpl
          - os: windows-latest
            CMD_BUILD: pyinstaller --clean -y --distpath ./dist/win img2zpl.spec
            OUT_FILE: win/img2zpl.exe
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    
    - run: pip install -r requirements.txt

    - name: Package Application
      run: ${{ matrix.CMD_BUILD }}
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/${{ matrix.OUT_FILE }}
